### ISSUE TITLE
Questions about Adakv application

### ISSUE THREAD

**Issue by duyuxuan1486** [FFY0/AdaKV#5]
你好！这是一项激动人心的工作。同时我想请问一下，我将如何让AdaKV/csrc/csrc/cuda_api.cu中的update代码替换原本kv cache update函数？需要什么指令进行操作呢？例如：编译，函数替换等

**Comment by FFY0** [comment]
你好，你是想要使用常规的Cache布局来支持AdaKV吗？目前AdaKV的实现是和我们的DynamicCacheSplitHeadFlatten类，cuda内核，以及FlashAttention的flash_attn_varlen_func api相绑定的。如果考虑使用常规的update函数来支持的话，需要将每个head的Cache分离进行管理，会导致较差的运算效率，这个对应的类我们已经注释掉了：位于AdaKV/adaptive_snapkv/monkeypatch/snapkv_utils.py“DynamicCacheSplitHead”。如果想要启用这个类的话，需要更改一下adaptive_mistral_hijack.py中对应的attention运算函数，我们建议直接使用当前提供的内核来支持AdaKV高效的运算，相关的内容可以参见一下这个[issue](https://github.com/FFY0/AdaKV/issues/2)

**Comment by duyuxuan1486** [comment]
好的，非常感谢你的回答。另外我还有一个有关于cuda内核的问题如下：我们是不是可以通过自己编写的.cu语言来实现一些目前api还没有的功能，例如：在矩阵相乘时，跳过指定行从而实现加速；在进行prune操作时，为不同head动态进行缓存（正如Adakv）。这些操作从理论上可以更进一步进行加速并保存更好的效果。

**Comment by FFY0** [comment]
您说的是对的，定制化的kernal对高效算法往往有着很大的帮助。这一方面需要在理论上针对性地设计高效的加速算法，另一方面需要定制kernel为这些算法提供支持，正如AdaKV一样。

**Comment by duyuxuan1486** [comment]
十分感谢您详细的回答！同时，我想再请问一下目前有哪些好的工具或者教程有助于我们编写对应算法所需的kernel吗？

**Comment by FFY0** [comment]
你可以参考这些仓库，或许有所帮助： https://github.com/Tony-Tan/CUDA_Freshman  https://github.com/srush/Triton-Puzzles

**Comment by duyuxuan1486** [comment]
再次感谢！
